### ISSUE TITLE
Invalid `Podfile` file: The target already has a platform set..

### ISSUE THREAD

**Issue by sanketsw** [rhanb/nativescript-bottombar#16]
Installing pods...

> [!] Invalid `Podfile` file: The target `Pods-GROCERIES` already has a platform set..
> 
>  from /Users/sanketsw/git/Groceries/GROCERIES/platforms/ios/Podfile:23
>  use_frameworks!
>  >  platform :ios, '8.0'
>  pod 'MiniTabBar', :git => 'https://github.com/rhanbIT/MiniTabBar.git'

> Processing node_modules failed. Error: Command pod failed with exit code 1

Here is how my podFile looks after tns run ios

[Podfile.txt](https://github.com/rhanbIT/nativescript-bottombar/files/1046864/Podfile.txt)

**Comment by rhanbIT** [comment]
This is weird, can you tell me the steps to reproduce this?

**Comment by sanketsw** [comment]
I created standard Groceries app from the tutorial. Added following modules (package.json attached) and ran tns run ios and it failed with this. If i remove nativescript-bottombar, it works fine.

My got repository here: https://github.com/sanketsw/Groceries 

[package.json.txt](https://github.com/rhanbIT/nativescript-bottombar/files/1047079/package.json.txt)

**Comment by rhanb** [comment]
@sanketsw , try to change the Podfile of the `nativescript-bottombar` and remove the line `platform :ios, '8.0'`. then remove the platform folder and then run `tns run ios`

**Comment by rhanb** [comment]
@sanketsw , should work with the latest version of the plugin `3.0.7`.
