### ISSUE TITLE
Text does not show under selected tab on bottom bar

### ISSUE THREAD

**Issue by anuragd7** [rhanb/nativescript-bottombar#20]
Hi @rhanbIT
Am creating a new issue as the [other issue](https://github.com/rhanbIT/nativescript-bottombar/issues/14) has been closed by @Linoman.

As suggested by you I have moved the initialisation to the constructor. Now everything works fine on android but I observe the following on IOS

On tns run ios the text does not show under the initially selected tab.
When I navigate away from the initially selected tab and then return to it, the selected colour shows correctly but the text below the picture does not display correctly.

You can observe this issue in this repo (https://github.com/anuragd7/bottomBarExample/tree/master/app)

**Comment by rhanb** [comment]
Same as #26
