### ISSUE TITLE
"selectItem" API is not working properly on IOS in {N}3 App.

### ISSUE THREAD

**Issue by anuragd7** [rhanb/nativescript-bottombar#26]
Hi, 

I am using your plugin in my {N} App. I am changing the tab on URL change, for that I am using your "selectItem" API. While doing that the icon of the respective tab is getting highlighted but the name of that tab is not showing up. But If I change the tab by clicking it, then the name of the tab shows with the animation.

Here is My environment detail.
nativescript     3.1.2
tns-core-modules 3.1.0
tns-android      3.1.1
tns-ios          3.1.0 

And here is my package.json.
"angular/animations": "~4.1.0",
"angular/common": "~4.1.0",
"angular/compiler": "~4.1.0",
"angular/core": "~4.1.0",
"angular/forms": "~4.1.0",
"angular/http": "~4.1.0",
"angular/platform-browser": "~4.1.0",
"angular/platform-browser-dynamic": "~4.1.0",
"angular/router": "~4.1.0",
"nativescript-angular": "^3.1.2",
"nativescript-bottombar": "^3.0.4",
"tns-core-modules": "^3.1.0"

Please help.

**Comment by kmuthukrishnan** [comment]
Hi @rhanb 
I seem to be facing a similar issue. Here are the facts -
I am using the nativescript-bottom bar plugin in my project to provide the main tabs for my application - say Tab1, Tab2 and Tab3. (Thanks @rhanb !)

When I click on a tab, say Tab2, it works perfectly fine. 
However here is the problem I am facing -  
from Tab 2, I am allowing users to create some content through a series of views. On the last view, I am allowing the user to submit their data and then navigating them back to Tab2. In such a case, the navigation is working fine, but on the view of the tabs below, the name of Tab 2 does not appear. I have to click the tab again to make the name appear.
I am seeing this behavior only in iOS, not on android. 

@rhanb , Can you help, please?

@anuragd7 , Is this similar to an issue you are facing? Did solve your issue?

Katy

**Comment by rhanb** [comment]
Hi @kmuthukrishnan and @anuragd7 ,

Thanks for you explanations and your details, I easily got your problem. And yes I managed to reproduce and effectively it's only on iOS. This issue actually comes from the Swift library I'm integrating which you can find here: https://github.com/rhanb/MiniTabBar . 
It's a Fork I did of the original library to implement new features but unfortunately I'm not really good at Swift (never practiced it before). 

So This issue may take a while to be fixed, but will do my best and I'll ping you when it will be fixed 😄

**Comment by kmuthukrishnan** [comment]
Hi @rhanb,

Thanks for your quick response. Please do let me know when it is fixed, I
am waiting for this upgrade so I can use the cool bottom bar. :)

regards
Krithika

**Comment by kmuthukrishnan** [comment]
Hi rhanb,

Please do update me if you have had a chance to progress this. Waiting for
the update! Thanks!

@kmuthukrishnan

**Comment by rhanb** [comment]
Hi,

Still dont have time to work on the Swift part. Please feel free to make a PR on this repo:

https://github.com/rhanb/MiniTabBar

I'll keep you up to date :)

**Comment by nicHoch** [comment]
Hi any progress on the selectItem issue for ios?

**Comment by rhanb** [comment]
@nicHoch it's a work in progress, put some time in it but didn't find yet the solution

**Comment by rhanb** [comment]
Hi everyone,

I finally managed to find where the issue comes from. I tested it out, it works now, I didn't change the plugin source code so you don't have to upgrade the version you just have to delete your platforms folder and re-build your app, the latest Pod version will be automatically downloaded.
(https://github.com/rhanb/MiniTabBar)
