### ISSUE TITLE
Different versions between Github and Npm

### ISSUE THREAD

**Issue by AdeilsonSilva** [rhanb/nativescript-bottombar#29]
The version in npm is still 2.1.4. Is that on purpose? In order to get the latest version I had to use

```
npm install https://github.com/rhanb/nativescript-bottombar
```

Just letting you know, in case it was a mistake.

**Comment by rhanb** [comment]
yes that's my mistake I released the `2.1.4` after the `3.0.4` so thats why when you install threw npm you get the last one But `2.1.4`is made for NS2.x.

`npm install nativescript-bottombar@3.0.4` is better ;) 

Thanks for the concern 😄
