### ISSUE TITLE
/tns-core-modules/ui/core/bindable/bindable"' has no exported member 'Bindable'

### ISSUE THREAD

**Issue by Acanguven** [rhanb/nativescript-bottombar#31]
Couldn't manage to compile plugin. 

`node_modules/nativescript-bottombar/index.d.ts(3,10): error TS2305: Module '"project/node_modules/tns-core-modules/ui/core/bindable/bindable"' has no exported member 'Bindable'.`

package.json
"tns-core-modules": "~3.1.0",

**Comment by rhanb** [comment]
#29
