### ISSUE TITLE
Error: Could not find module 'ui/core/proxy'

### ISSUE THREAD

**Issue by bitzage11** [rhanb/nativescript-bottombar#33]
file:///app/tns_modules/nativescript-bottombar/src/common.js:4:22: JS ERROR Error: Could not find module 'ui/core/proxy'. Computed path '/Users/awaisatiq/Library/Developer/CoreSimulator/Devices/D2A489E5-B071-4354-967D-36FAD8BDCB9A/data/Containers/Bundle/Application/4ECF1C8C-1AD4-4E46-BB70-2A9BAEA25550/PointStop.app/app/tns_modules/ui/core/proxy'.
Aug 25 15:00:22 Awaiss-iMac com.apple.CoreSimulator.SimDevice.D2A489E5-B071-4354-967D-36FAD8BDCB9A.launchd_sim[863] (UIKitApplication:com.akkastech.PointStop[0x9787][885][2344]): Service exited due to Segmentation fault: 11

Package.json
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.akkastech.PointStop",
    "tns-ios": {
      "version": "3.1.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.2.0",
    "@angular/common": "~4.2.0",
    "@angular/compiler": "~4.2.0",
    "@angular/core": "~4.2.0",
    "@angular/forms": "~4.2.0",
    "@angular/http": "~4.2.0",
    "@angular/platform-browser": "~4.2.0",
    "@angular/router": "~4.2.0",
    "nativescript-angular": "~4.2.0",
    "nativescript-bottombar": "^3.0.6",
    "nativescript-carousel": "^3.1.0",
    "nativescript-checkbox": "^2.1.11",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.2",
    "tns-core-modules": "~3.1.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "~0.5.0",
    "typescript": "~2.4.2"
  }
}

**Comment by rhanb** [comment]
ok, i wanted to make a quick fix with the latest version but did it too fast now it's broke. please install version 3.0.4

**Comment by demetrio812** [comment]
Actually for me the 3.0.5 is working, it's the 3.0.6 that it's giving this problem

**Comment by rhanb** [comment]
Thanks @demetrio812 ,

Thanks to your comment, I already know how to fix the issue without even thinking about it 😄

**Comment by kumaran-dena** [comment]
I am also facing this issue with version 3.0.4. And i am not tried with version 3.0.6.

As @demetrio812 mentioned, Version 3.0.5 is working fine for me too. 

@rhanb I am waiting for your next fix with the latest version.

**Comment by rhanb** [comment]
@kumaran-dena , basically this issue is due to NS2.x support and NS3.x support. I made a mistake while updating this plugin to 3.0.6 which was made for NS3 but I didn't updated the tns-core-modules to NS3.x so you got this error.
3.0.4 was supposed to be 2.1.5, 3.0.5 is ok etc.. 
And there is no difference between 3.0.4 and 3.0.6 so stick to it for now 👍

**Comment by kumaran-dena** [comment]
thank you @rhanb. i will keep stick to it for now.

**Comment by Sumit-ignistec** [comment]
When should i expect  the fixes please, i am not able to bump my new version

**Comment by rhanb** [comment]
@Sumit-ignistec , @kumaran-dena , @demetrio812 , @bitzage11 : issue fixed with the latest version: `3.0.7`. Sorry for taking so much time 😄
