### ISSUE TITLE
cannot read property android of null, undefined

### ISSUE THREAD

**Issue by khanyuriy** [rhanb/nativescript-bottombar#37]
Hi!
I am trying to use nativescript-bottombar@3.0.5 with nativescript-angular (tns --version, 3.2.0).
I copy pasted code from demo app.component to my test component. But can not get it worked.
I'v got this err in console.
JS: tabLoaded
JS: ERROR TypeError: Cannot read property 'android' of null
JS: ERROR CONTEXT [object Object]
on emulator i see blank page with text Cannot read property 'android' of null, undefined.
Where i could made mistake?

**Comment by rhanb** [comment]
This issue comes from your icons. Look at the end of the README in the "Ressources" section. If you don't manage to make it work please provide code and a screenshot of your ressources folder of the android part.

Thanks

**Comment by khanyuriy** [comment]
That's right! Thank you!
