### ISSUE TITLE
IOS: inactiveColor not working

### ISSUE THREAD

**Issue by nicHoch** [rhanb/nativescript-bottombar#38]
i use following setting in version: 3.0.4

```
	bottomBar.hide = false;
	bottomBar.titleState = TITLE_STATE.ALWAYS_SHOW;
	bottomBar.inactiveColor = "red";
	bottomBar.accentColor = "deepskyblue";
	bottomBar.colored = false;
	bottomBar.uncoloredBackgroundColor = "ghostwhite"
```
in android it is working fine but on ios I got:

![screen shot 2017-10-03 at 21 28 44](https://user-images.githubusercontent.com/2226714/31144770-02f5464e-a882-11e7-9336-6139af4d2e93.png)

the text color of all inactive items is back and not red and the icon color of each item is the accentColor regardless of active or not.

**Comment by rhanb** [comment]
@nicHoch ,

Thanks for the report! I need to work on the Swift library, I'll ping you when it's fixed 😄

**Comment by rhanb** [comment]
@nicHoch ,

I updated the Swift side, it should work now. To get the latest version of the Swift Library you just have to:

```
- rm -rf platforms/ios
- npm run ios
```

Since it directly point to the github repo and I updated it no need of a new version on the plugin and deleting the ios platform and run the application again will download directly the latest version on the github repo.

**Comment by nicHoch** [comment]
it is still the very same as in the initial description. the text color of all inactive items is back and not red and the icon color of each item is the accentColor regardless of active or not.

please reopen

**Comment by rhanb** [comment]
that's weird it was working for me. thanks for the help will check this out asap as I'll fix the hard crash issue. but feel free to make a pr on my fork @nicHoch

**Comment by rhanb** [comment]
should be working after #45 fix
