### ISSUE TITLE
BottomBar doesn't appear with Webpack

### ISSUE THREAD

**Issue by alexandruantonica** [rhanb/nativescript-bottombar#40]
Hi @rhanb 
I have installed the `nativescript-dev-webpack`, everything is fine but when I run `npm run start-android-bundle` the BottomBar disappear.
I tried to run `tns run android` but there it works. 
The problem is only on Android with `npm run start-android-bundle`.

```
"nativescript-cli" : "3.1.3",
"tns-core-modules" : "3.1.1",
"tns-android" : "3.2.0"
"tns-ios" : "3.2.0"
```
package.json
```
"@angular/*" : "4.1.3",
"nativescript-bottombar": "3.0.5",
```

Thanks.

**Comment by rhanb** [comment]
Hi @alexandruantonica ,

Thanks for the details. Do you have any error output please? I honestly never tried to webpack an app with the `nativescript-bottombar`.

**Comment by alexandruantonica** [comment]
Hi @rhanb ,

Here is the interesting part. I have no console errors, no warnings or something else. 
The plugin works like without webpack just it hide the BottomBar. I mean the `loaded` event are triggered because I received a console log with `BottomBarLoaded`.

**Comment by rhanb** [comment]
That's effectively interesting and weird.. I'll try to reproduce the issue. You use Angular, right? Just to make sure.

**Comment by alexandruantonica** [comment]
Yes, Angular. You have some details above.
Let me know if you need any other informations.

**Comment by rhanb** [comment]
I will 👍

**Comment by demetrio812** [comment]
Hello, any news about this? I'm having this problem too (and it's quite an important one), let me know how I can help

**Comment by rhanb** [comment]
Hi @demetrio812 , if you can create a repo with a simple angular project with only the BottomBar and webpack it, it would save me some time to find out a solution

**Comment by alexandruantonica** [comment]
@rhanb The issue was solved. There was a problem with my project. 
Thanks :)

**Comment by demetrio812** [comment]
same for me (as I told you on slack) thanks @rhanb !
