### ISSUE TITLE
Bottombar breaks on iOS with Fancy-Calender

### ISSUE THREAD

**Issue by LeonBorlinghaus** [rhanb/nativescript-bottombar#43]
Hi,

This issue is releated to this issue:
https://github.com/rhanb/nativescript-fancy-calendar/issues/13#issuecomment-338301142

The problem is that the Fancy-Calendar is making problems on iOS devices. When this happens the bottombar breaks as well.

**Comment by rhanb** [comment]
Hi @LeonBorlinghaus ,

Thanks for the feedback. I thought it was an other issue from the BottomBar, since it's directly related to the fancy calendar plugin I will close this one and let the issue on the calendar repo open. Since fixing the issue on fancy calendar should let the bottombar working
