### ISSUE TITLE
Bottombar is crashing  in ios 

### ISSUE THREAD

**Issue by ravidoki** [rhanb/nativescript-bottombar#45]
Hello,

I am trying to use bottombar in both android and ios. I am trying to build the android app on windows and ios app on clould using side kick.

Android app is working fine but ios app is crashing. The ios app crashingas soon as I am navigating to the home page.

After long debugging,  I found that it is not able to intialize MiniTabBar and app is crashing

```
 var BottomBar = (function(_super) {
            __extends(BottomBar, _super);
            function BottomBar() {
                var _this = _super.call(this) || this;
                var items = new Array();
                _**this.nativeView = new MiniTabBar({**
                    items: items,
                    titleState: 0
                });
 
```

```
 <StackLayout row="1" orientation="horizontal">
            <BottomBar verticalAlignment="center"
                       row="1" [items]="items" [hide]="hidden" [titleState]="titleState"
                       (loaded)="tabLoaded($event)" (tabSelected)="tabSelected($event)"
                       [inactiveColor]="inactiveColor" [accentColor]="accentColor" colored="true"></BottomBar>

        </StackLayout>
```

**Comment by rhanb** [comment]
@ravidoki provide code please

**Comment by ravidoki** [comment]
Hi @rhanb, Thanks for reply.

Here it is

```
import { Component } from "@angular/core";
import { Page } from "ui/page";
import { Router } from "@angular/router";
import { registerElement } from 'nativescript-angular';
import { BottomBar, BottomBarItem, TITLE_STATE, SelectedIndexChangedEventData, Notification } from 'nativescript-bottombar';

registerElement('BottomBar', () => BottomBar);

@Component({
  selector: "nsapp",
  templateUrl: "pages/home/home.html",
  styleUrls: ["pages/home/home-common.css", "pages/home/home.css"],
})

export class HomeComponent {
  public hidden: boolean;
  public titleState: TITLE_STATE;
  public _bar: BottomBar;
  public inactiveColor: string;
  public accentColor: string;

  constructor(private page: Page, private route: Router) {
    //page.actionBarHidden = true;
  }

  public items: Array<BottomBarItem> = [

    new BottomBarItem(0, "Dashboard", "ic_paperplane", "#b0245f"),
    new BottomBarItem(1, "Compose", "ic_paperplane", "#b0245f", null),
    new BottomBarItem(2, "Message Log", "ic_paperplane", "#b0245f", null)
    // new BottomBarItem(3, "Contacts", "ic_favorite", "#b0245f", null),
    // new BottomBarItem(4, "Settings", "ic_settings", "#b0245f", null)
  ];

  tabLoaded(event) {
    console.log("barLoaded");
    this._bar = <BottomBar>event.object;
    this.hidden = false;
    this.titleState = TITLE_STATE.SHOW_WHEN_ACTIVE;
    this.inactiveColor = "black";
    this.accentColor = "white";
  }

  tabSelected(args: SelectedIndexChangedEventData) {
    switch (args.newIndex) {
      case 0 :this.route.navigate(['/home/dashboard'] );
        break;
      case 1 : this.route.navigate(['/home/message']);
        break;
      case 2: this.route.navigate(['/home/messagelog']);
        break;
    }
  }
}
```

**Comment by rhanb** [comment]
Could you also provide the error output please?

**Comment by nicHoch** [comment]
hi the new swift updates after ( #38 )  also crate also a crash on ios for me:
 
i only see "fatal error: Index out of range" in the console - as soon as i navigate to a page with a bottom bar.

**Comment by rhanb** [comment]
@nicHoch  Thanks for pointing out that it comes with the latest Swift update. Will dig into that thanks :)

**Comment by ravidoki** [comment]
@rhanb  I didn't get any error . I am also having same issue as @nicHoch .

**Comment by codeback** [comment]
I'm having this error too:  "fatal error: Index out of range".

**Comment by codeback** [comment]
@rhanb, The issue is due to call **setItems** on **init** function in the file **MiniTabBar.swift**:
```
...
public init(items: [MiniTabBarItem], titleState: TitleState) {
        self.colored = false
        self.titleState = titleState
        self.animatedHide = false
        self.positionY = CGFloat(0)
        self.uncoloredBackgroundColor = UIColor(white: 1.0, alpha: 0.8)
        super.init(frame: CGRect.zero)
        self.backgroundColor = self.uncoloredBackgroundColor

        self.addSubview(visualEffectView)
        keyLine.backgroundColor = UIColor(white: 0.9, alpha: 1.0)
        self.addSubview(keyLine)
        print("im setting items now")
        self.setItems(items)
}
...
```  
If I comment the last line, it works. Please can you validate it?

Thank you in advance

**Comment by rhanb** [comment]
@codeback , thank you very much it helps a lot ! I will check this out asap 👍

**Comment by rhanb** [comment]
I will work on it this week-end, don't have time before unfortunately. Sorry for the hard crash on iOS 😞

**Comment by zLinz** [comment]
@rhanb Thank you very much!

**Comment by ravidoki** [comment]
Thanks @rhanb .

**Comment by bremkesti** [comment]
Is there any news on this? Even if its just a temporary fix to apply til a new update roles out-

**Comment by peterkrieg** [comment]
The code fix by @codeback worked for me at first, but now it doesn't for some reason (it also only worked for emulator, and not device testing, no idea why). 

So now I have no way of fixing this and am currently only running android for now.  Anyone else have a temporary fix they know of?

**Comment by shiv19** [comment]
I am using a bottom bar made using flexbox layout as a temporary fix for this
`<android>
                    <btb:BottomBar row="2" items="{{ items }}"
                        hide="{{ hidden }}" titleState="{{ titleState }}"
                        loaded="tabLoaded" unloaded="tabUnLoaded"
                        inactiveColor="{{ inactiveColor }}"
                        accentColor="{{ accentColor }}" colored="true">
                    </btb:BottomBar>
                </android>
                <ios>
                    <FlexboxLayout row="2" backgroundColor="#4099ff" flexDirection="row" 
                        justifyContent="space-around" padding="10">
                        <Image tap="tabSelected" newIndex="0" height="30" src="res://home" />
                        <Image tap="tabSelected" newIndex="1" height="30" src="res://icstatus" />
                        <Image tap="tabSelected" newIndex="2" height="30" src="res://trainme" />
                        <Image tap="tabSelected" newIndex="3" height="30" src="res://icexplore" />
                    </FlexboxLayout>
                </ios>`

**Comment by rhanb** [comment]
@bremkesti and @peterkrieg , I unfortunately didn't get enough time to deep dive into this issue. But will def keep you up to date when I'll get time 👍 

Thanks a lot @shiv19 for the share, hope it can help.

**Comment by Jay268** [comment]
@rhanb 

I am also having same issue iOS crashing the app. Let us know when you share a stable update for this.

**Comment by shiamalon** [comment]
Having the exact same issue :| Is there any way I can help?

**Comment by rhanb** [comment]
This issue is fixed. 

as @codeback was saying, it was coming from this :

```typescript
self.setItems(items)
```

In the Swift demo everything was working well, but it wasn't working in the NativeScript plugin because of this:

```typescript
let items = new Array<any>();
this.nativeView = new MiniTabBar({
       items: items,
       titleState: TITLE_STATE.SHOW_WHEN_ACTIVE
});
```

I am initialising the MiniTabBar with an empty array in the constructor to make sure to have an instance of it even if the plugin consumer doesn't set any BottomBarItem or is they are not set yet when the class is constructed.

But in the latest update of the swift library I change the code of initialisation,  I wasn't checking if the array passed as a parameter was empty or not, so using the library withing the NativeScript plugin was making the error: 

`fatal error: Index out of range`

So I fixed that on the Swift side. 
Follow those instructions to fix this issue: 

```
- tns plugin remove nativescript-bottombar
- rm -rf platforms
- tns plugin add nativescript-bottombar
- tns run ios
```

**Comment by peterkrieg** [comment]
Thank you very much @rhanb !

**Comment by FranciZ** [comment]
@rhanb 

Not sure if it's the same error but bottombar is still crashing for me on iOS. Working normally on Android. Logs below.

`Fatal error: Index out of range`

It fails on line `194` in `MiniTabBar.swift`. Also attaching a screenshot of XCode debugger.

<img width="1075" alt="screen shot 2017-12-23 at 20 22 50" src="https://user-images.githubusercontent.com/2536035/34322127-655aa608-e81f-11e7-9c45-636a4e474239.png">

**Comment by rhanb** [comment]
@FranciZ , are you sure you have the latest iOS version of the library? Did you `rm` your platforms folder and then re run your build?

**Comment by FranciZ** [comment]
@rhanb I did follow the instruction exactly as written. I managed to get it working as I explain in the previous comment but I did have to edit `MiniTabBar.swift`. The icon name typo was my bad.

**Comment by rhanb** [comment]
@FranciZ can you provide the code of the function `setItems` in your `MiniTabBar.swift` file please?

**Comment by FranciZ** [comment]
@rhanb Here you go.

```swift
public func setItems(_ items: [MiniTabBarItem]) {
        if (self.itemViews.count > 0) {
            for v in self.subviews {
                v.removeFromSuperview()
            }
            self.itemViews = [MiniTabBarItemView]()
        }
        
        if (items.count > 0) {
            for item in items {
                let itemView = MiniTabBarItemView(item, self)
                itemView.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(MiniTabBar.itemTapped(_:))))
                self.itemViews.append(itemView)
                self.addSubview(itemView)
            }
            if (self.itemViews.count > 0) {
                self.selectItem(0, animated: true);
            }
        }
    }
```

**Comment by rhanb** [comment]
@FranciZ , I don't manage to reproduce the error. Since the latest update of the swift library, it works fine on my side, if you still got the error, could you provide a github repo to reproduce the error? Thanks 👍

**Comment by FranciZ** [comment]
@rhanb Works now without issues. Could be the version was the issue. Thanks!
