### ISSUE TITLE
Native script bottom bar remove shift mode animation

### ISSUE THREAD

**Issue by Jay268** [rhanb/nativescript-bottombar#48]
@rhanb 

I am using bottom bar in native script. I am able to setup it and working as intended.

But what my requirement is i need to remove shift mode animation while moving from one tab to another.
I have tried to customize style but not exactly giving what i need. 

Your suggestions are appreciated. And also let me know if any further information you need.

**Comment by rhanb** [comment]
If you want to remove the shift animation, you should change the titleState property and use the value `ALWAYS_HIDE` or `ALWAYS_SHOW`.

**Comment by rhanb** [comment]
Unfortunately you cant remove the shift animation with your titleState property set to `SHOW_WHEN_ACTIVE`

**Comment by Jay268** [comment]
@rhanb 

Thanks for your reply.

I tried by setting `ALWAYS_HIDE` it looks like animation effect is removed with that as intended. But it's showing kind of bubble / ripple effect while moving on another tab.

Any suggestion on that note ? how to manage that ?

**Comment by rhanb** [comment]
You can't change that, because it's by default in the native library which follow the Bottom Navigation google specs 😄
