### ISSUE TITLE
Hidden Bottom-bar when keyboard is open

### ISSUE THREAD

**Issue by edrick27** [rhanb/nativescript-bottombar#56]
Hi i'am using the BottomBar to Natiscript, It's awesome, but when you open the keyboard the bottombar stays on the keyboard, is there no way to hide it?

**Comment by rhanb** [comment]
@edrick27 , you can use the property `hide` and set it to true when you want to hide the `BottomBar`

**Comment by edrick27** [comment]
https://drive.google.com/open?id=1lZL3uTv7-kmfHe9APd8dW3Oo9zK5_M0m

**Comment by edrick27** [comment]
Perfect thanks, yes but my problem is different, when I open the keyboard it looks like in the previous image. Is there any way to prevent that from happening?
