### ISSUE TITLE
[iOS] Color issues when not using data-binding (angular)

### ISSUE THREAD

**Issue by vcooley** [rhanb/nativescript-bottombar#63]
For iOS using "regular", non data-bound properties can cause problems. For instance I am attempting to set the `inactiveColor` and `accentColor` properties, as I do not want them to change. However, this causes all of the icons to be set to the color of the `accentColor`. Changing them to bound properties fixes the problem, but it is still undesired and very confusing behavior.

Here is an example that causes the issue:
```html
<BottomBar row="1" [items]="navItems" [titleState]="titleState" inactiveColor="rgb(117, 117, 117)" accentColor="blue"></BottomBar>
```

And here is the equivalent, working version. Notice the bound properties and the extra single quotes.
```html
<BottomBar row="1" [items]="navItems" [titleState]="titleState" [inactiveColor]="'rgb(117, 117, 117)'" [accentColor]="'blue'"></BottomBar>
```

**Comment by rhanb** [comment]
Should be fixed with the pre-release 4.0.0-rc1.1. Be careful, there is a lot of breaking changes.
