### ISSUE TITLE
Typescript error when registering BottomBar element (Angular)

### ISSUE THREAD

**Issue by kjlaw89** [rhanb/nativescript-bottombar#65]
Typescript prevents me from adding BottomBar to my app through registerElement because conflict in a property. Project is using Typescript 2.6.2 and Nativescript 3.4.3.

Error:
[ts]
Argument of type '() => typeof BottomBar' is not assignable to parameter of type 'ViewResolver'.
  Type 'typeof BottomBar' is not assignable to type 'ViewClass'.
    Type 'BottomBar' is not assignable to type 'View'.
      Types of property 'hide' are incompatible.
        Type 'boolean' is not assignable to type '(duration?: string | number) => Promise<void>'.

**Comment by noumaans** [comment]
Are you using:

```ts
import { registerElement } from 'nativescript-angular';

registerElement('BottomBar', () => BottomBar);
```

It seems to work with TS 2.6.2. Do you mind sharing your code?

**Comment by rhanb** [comment]
Closing since no reply
