### ISSUE TITLE
Newbie question... how to correctly run the sample app?

### ISSUE THREAD

**Issue by hanglearning** [rhanb/nativescript-bottombar#66]
Sorry, please bear with me 😂I'm still a bit new to NativeScript.

So after I downloaded the project, I cd into the demo-ng folder, and

tns platform add ios

and then, tns run ios --emulator, but got this error
npm ERR! Could not install from "../../../../rhanb/Documents/DevLove/OSS/NativeScript/nativescript-bottombar" as it does not contain a package.json file.

![image](https://user-images.githubusercontent.com/13460425/38682285-45405550-3e9d-11e8-9600-026f2fd2472b.png)

Can anyone please tell me how I can solve this problem?

Thanks!

**Comment by rhanb** [comment]
Run `npm run demo.ios` or `npm run demo.android` at the root of the folder, not the `demo` one.
