### ISSUE TITLE
update notification on iOS

### ISSUE THREAD

**Issue by marcuschoong** [rhanb/nativescript-bottombar#75]
refer to case #35, its work on the android and update the notification number.
but the notification is not update on the iOS platform. 
following is my coding:

> let bottomBarView: BottomBar = <BottomBar>this.page.getViewById("bottomBar");
> bottomBarView.setNotification(counter + "", 0)

Please help.

**Comment by rhanb** [comment]
@marcuschoong Should be fixed with the pre-release 4.0.0-rc1.1. Be careful, there is a lot of breaking changes.
