### ISSUE TITLE
Support TNS 5.0.0

### ISSUE THREAD

**Issue by edyrkaj** [rhanb/nativescript-bottombar#76]
Hi I have been using this module on previous version of nativescript. It has problems with xcode IOS build.
Does this support latest version 5.0.0?

Als when you try to run or build for ios: 
warning: Swift 3 mode has been deprecated and will be removed in a later version of Xcode. Please migrate "MiniTabBar" to Swift 4.2 using "Convert > To Current Swift Syntax…" in the Edit menu. (in target 'MiniTabBar')

You have prepared this pod file before and looks like something needs to be change here:
https://github.com/rhanb/nativescript-bottombar/blob/master/platforms/ios/Podfile

Thank you.

**Comment by rhanb** [comment]
Should be fixed with the pre-release `4.0.0-rc1.1`. Be careful, there is a lot of breaking changes.
