### ISSUE TITLE
How do I use android svg files as icon located in drawable folder in bottombar item component?

### ISSUE THREAD

**Issue by tareq89** [rhanb/nativescript-bottombar#78]
First, thank you very much for this plugin. I have some android svg files in in res/drawable folder. I tried to use those icon files in bottom bar component as icon, ex: "icon_name", "res://icon_name", but none of this is working. Can anyone give me any idea how to achieve this?

**Comment by rhanb** [comment]
@tareq89 unfortunately svg files are not supported. Due to NativeScript itself and its `image-source` module which don't allow `svg` format.
Supporting `svg` would mean to add the plugin `nativescript-svg` as a dependency; this is not planned.
