### ISSUE TITLE
How can I get the bottombaritem text

### ISSUE THREAD

**Issue by marcuschoong** [rhanb/nativescript-bottombar#83]
Thanks for this awesome library. by reference with https://github.com/rhanb/nativescript-bottombar/issues/80.

May I know how to get the bottombaritem text instead of the event.newIndex by referring the following declaration? 

> xml
> <GridLayout rows="*, auto">
>     <router-outlet></router-outlet>
> 
>     
>     <BottomBar id="bottomBar" row="1" [items]="bottomBarItems2" [hide]="hidden" [titleState]="titleState" (loaded)="tabLoaded($event)"
>         (tabSelected)="tabSelected($event)" [inactiveColor]="inactiveColor" [accentColor]="accentColor" colored="true"
>         class="chat_tabBarContainer"></BottomBar>
> 
> </GridLayout>

> ngOnInit() {
> ...
> private bottomBarItems2 = [];
> var item = new BottomBarItem();
>         item.icon = 'res://ic_menu_chat_1';
>         item.title = "Chat";
>         this.bottomBarItems2.push(item);
>         if (this.hasTicketTagModuleAndAccess()) {
>             var item2 = new BottomBarItem();
>             item2.icon = 'res://ic_menu_ticket_1';
>             item2.title = "Ticket";
>             this.bottomBarItems2.push(item2);
>         }
>         var item3 = new BottomBarItem();
>         item3.icon = 'res://ic_menu_setting_1';
>         item3.title ="Setting";
>         this.bottomBarItems2.push(item3);
> }

my question is how can I get the BottomBarItems title on the tabSelected event.

**Comment by rhanb** [comment]
I don't understand the question, please provide more infos or code

**Comment by marcuschoong** [comment]
@rhanb I updated the question, my question is how can I get the selected BottomBarItem text like chat, ticket or setting.

**Comment by rhanb** [comment]
well since you have the index in the event you can do this easly:
```typescript
tabSelected(event: TabSelectedEventData) {
    let selectedTabTitle: string;
    switch (event.newIndex) {
      case 0:
        selectedTabTitle = item.title
          break;
      case 1:
        selectedTabTitle = item2.title
      .
      .
    }
  }
```

I suggest to use an array instead on multiple objects

**Comment by rhanb** [comment]
This issue is not supposed on github by the way, stackoverflow would have been more suitable
